using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace resumeApp
{
    public static class ThemeColor
    {
        public static List<string> colorList = new List<string>()
                                                {
                                                    "#B0BF1A",
                                                    "#7CB9E8",
                                                    "#C9FFE5",
                                                    "#B284BE",
                                                    "#5D8AA8",
                                                    "#00308F",
                                                    "#72A0C1",
                                                    "#AF002A",
                                                    "#F2F0E6",
                                                    "#F0F8FF",
                                                    "#84DE02",
                                                    "#E32636",
                                                    "#C46210",
                                                    "#EFDECD",
                                                    "#E52B50",
                                                    "#9F2B68",
                                                    "#F19CBB",
                                                    "#AB274F",
                                                    "#D3212D",
                                                    "#3B7A57",
                                                    "#00C4B0",
                                                    "#FFBF00",
                                                    "#FF7E00",
                                                    "#FF033E",
                                                    "#9966CC",
                                                    "#A4C639",
                                                    "#F2F3F4",
                                                    "#CD9575",
                                                    "#665D1E",
                                                    "#915C83",
                                                    "#841B2D",
                                                    "#FAEBD7",
                                                    "#008000",
                                                    "#8DB600",
                                                    "#FBCEB1",
                                                    "#00FFFF",
                                                    "#7FFFD4",
                                                    "#D0FF14",
                                                    "#4B5320",
                                                    "#3B444B",
                                                    "#8F9779",
                                                    "#E9D66B",
                                                    "#B2BEB5",
                                                    "#87A96B",
                                                    "#FF9966",
                                                    "#A52A2A",
                                                    "#FDEE00",
                                                    "#6E7F80",
                                                    "#568203",
                                                    "#FF2052",
                                                    "#C39953",
                                                    "#007FFF",
                                                    "#F0FFFF",
                                                    "#F0FFFF",
                                                    "#DBE9F4",
                                                    "#89CFF0",
                                                    "#A1CAF1",
                                                    "#F4C2C2",
                                                    "#FEFEFA",
                                                    "#FF91AF",
                                                    "#21ABCD",
                                                    "#FAE7B5",
                                                    "#FFE135",
                                                    "#006A4E",
                                                    "#E0218A",
                                                    "#7C0A02",
                                                    "#1DACD6",
                                                    "#848482",
                                                    "#98777B",
                                                    "#BCD4E6",
                                                    "#9F8170",
                                                    "#FA6E79",
                                                    "#F5F5DC",
                                                    "#2E5894",
                                                    "#9C2542",
                                                    "#E88E5A",
                                                    "#FFE4C4",
                                                    "#3D2B1F",
                                                    "#967117",
                                                    "#CAE00D",
                                                    "#BFFF00",
                                                    "#FE6F5E",
                                                    "#BF4F51",
                                                    "#000000",
                                                    "#3D0C02",
                                                    "#54626F",
                                                    "#253529",
                                                    "#3B3C36",
                                                    "#BFAFB2",
                                                    "#FFEBCD",
                                                    "#A57164",
                                                    "#318CE7",
                                                    "#ACE5EE",
                                                    "#FAF0BE",
                                                    "#0000FF",
                                                    "#1F75FE",
                                                    "#0093AF",
                                                    "#0087BD",
                                                    "#0018A8",
                                                    "#333399",
                                                    "#0247FE",
                                                    "#A2A2D0",
                                                    "#00B9FB",
                                                    "#6699CC",
                                                    "#0D98BA",
                                                    "#5DADEC",
                                                    "#ACE5EE",
                                                    "#553592",
                                                    "#126180",
                                                    "#8A2BE2",
                                                    "#5072A7",
                                                    "#4F86F7",
                                                    "#1C1CF0",
                                                    "#DE5D83",
                                                    "#79443B",
                                                    "#0095B6",
                                                    "#E3DAC9",
                                                    "#DDE26A",
                                                    "#CC0000",
                                                    "#006A4E",
                                                    "#873260",
                                                    "#0070FF",
                                                    "#B5A642",
                                                    "#CB4154",
                                                    "#1DACD6",
                                                    "#66FF00",
                                                    "#BF94E4",
                                                    "#D891EF",
                                                    "#C32148",
                                                    "#1974D2",
                                                    "#FF007F",
                                                    "#08E8DE",
                                                    "#D19FE8",
                                                    "#FFAA1D",
                                                    "#3399FF",
                                                    "#F4BBFF",
                                                    "#FF55A3",
                                                    "#FB607F",
                                                    "#004225",
                                                    "#CD7F32",
                                                    "#737000",
                                                    "#964B00",
                                                    "#A52A2A",
                                                    "#6B4423",
                                                    "#AF6E4D",
                                                    "#cc9966",
                                                    "#1B4D3E",
                                                    "#FFC1CC",
                                                    "#E7FEFF",
                                                    "#7BB661",
                                                    "#F0DC82",
                                                    "#480607",
                                                    "#800020",
                                                    "#DEB887",
                                                    "#A17A74",
                                                    "#CC5500",
                                                    "#E97451",
                                                    "#8A3324",
                                                    "#24A0ED",
                                                    "#BD33A4",
                                                    "#702963",
                                                    "#536872",
                                                    "#5F9EA0",
                                                    "#91A3B0",
                                                    "#006B3C",
                                                    "#ED872D",
                                                    "#E30022",
                                                    "#FFF600",
                                                    "#A67B5B",
                                                    "#4B3621",
                                                    "#1E4D2B",
                                                    "#A3C1AD",
                                                    "#C19A6B",
                                                    "#EFBBCC",
                                                    "#78866B",
                                                    "#FFFF99",
                                                    "#FFEF00",
                                                    "#FF0800",
                                                    "#E4717A",
                                                    "#00BFFF",
                                                    "#592720",
                                                    "#C41E3A",
                                                    "#00CC99"
                                                };

        public static Color ChangeColorBrightness(Color color, double correctionfactor)
        {
            double red = color.R;
            double green = color.G;
            double blue = color.B;

            if(correctionfactor < 0)
            {
                correctionfactor = 1 + correctionfactor;
                red *= correctionfactor;
                green *= correctionfactor;
                blue *= correctionfactor;
            }
            else
            {
                red = (255 - red) * correctionfactor + red;
                green = (255 - green) * correctionfactor + green;
                blue = (255 - blue) * correctionfactor + blue;
            }
            return Color.FromArgb(color.A, (byte)red, (byte)green, (byte)blue);
        }
    }
}
